POST http://localhost/wp-json/joeee-booking/v1/user HTTP/1.1
content-type: application/json

{
    "email": "sepp@example.com",
    "first_name": "Sepp",
    "last_name": "Stuitz",
    "birthday": "1983-03-02",
    "nationality": 3,
    "street": "Kirchenstraße 32",
    "zip": "2499",
    "city": "Beijing",
    "country": 3
}