POST http://localhost/wp-json/joeee-booking/v1/room HTTP/1.1
content-type: application/json

{
    "active": true,
    "adults": 1,
    "description": "1",
​    "floor": 1,
    "image_url": "",
    "kids": 1,
    "number": "1",
    "price": 1,
    "single_room_supplement": 1,
}